spring:
  application:
    name: order_hub
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${POSTGRES_PORT:5432}/${DATABASE_NAME:order_hub}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      schema: order_service
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS order_service
      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

management:
  metrics:
    distribution:
      percentiles-histogram:
        all: true
      slo:
        "[http.server.requests]": 50ms,100ms,500ms,1s,2s
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - loggers

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

info:
  app:
    name: "Супер-пупер приложуха"
    version: "0.0.1"
    description: "Ну просто очень супер-пупер приложение богов!!"

server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    org.hibernate.org: ${LOGGING_LEVEL:DEBUG}